config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'reconciliations#index'

  resources :cash_flows, only: [:create, :index, :update, :destroy] do
    collection do
      post "add_transaction"
      delete 'delete_all'
    end
  end

  post "set_balance", to: "cash_flows#set_balance"
  post "reset_balance", to: "cash_flows#reset_balance"

  resources :reconciliations, only: [:new, :create, :index] do
    collection do
      delete 'delete_all'
      get 'download_pdf'
    end
  end

end

app/models/cash_flow.rb
class CashFlow < ApplicationRecord
  require 'csv'
  belongs_to :user
  scope :for_current_user, -> { where(user_id: Current.user.id) if Current.user }

  EXPECTED_HEADERS = %w[date description amount transaction_type].freeze

  validates :date, presence: true
  validates :description, presence: true
  validates :amount, presence: true, numericality: true
  validates :transaction_type, presence: true


  def self.import_from_csv(file, user)
    headers = nil
    CSV.foreach(file, headers: true) do |row|
      if headers.nil?
        headers = row.headers.map(&:strip).map(&:underscore)
        unless headers_match?(headers)
          return { success: false, error: "CSV headers must be: #{EXPECTED_HEADERS.join(', ')}" }
        end
      end
      # Parse the amount
      cash_flow_attributes = row.to_hash.transform_keys(&:underscore)
      cash_flow_attributes['amount'] = cash_flow_attributes['amount']&.gsub(/[[:space:]]/, '')&.tr('R$', '')
      cash_flow_attributes['amount'] = cash_flow_attributes['amount'].gsub('.', '')&.gsub(',', '.').to_f
      # Parse the date
        parsed_date = DateParser.parse(cash_flow_attributes['date'])
        if parsed_date[:success]
          cash_flow_attributes['date'] = parsed_date[:date]
        else
          return { success: false, error: parsed_date[:error] }
        end

      user.cash_flows.create!(cash_flow_attributes)
    end
    { success: true }
  end

  def self.headers_match?(headers)
    headers.sort == EXPECTED_HEADERS.sort
  end
end

app/controllers/cash_flows_controller.rb
class CashFlowsController < ApplicationController

  def new
    @cash_flow_records = CashFlow.for_current_user.all
  end

  def create
    unless params[:cash_flow].present?
      flash.now[:alert] = 'Please upload a CSV file.'
      @cash_flow_records = CashFlow.for_current_user.order(date: :asc) # Ensure transactions are loaded
      render :index, status: :unprocessable_entity
      return
    end

    @csv_file = params[:cash_flow][:file]

    # Check if the file has a valid content type
    unless validate_csv(@csv_file)
      flash[:alert] = 'Uploaded file must be a valid CSV format'
      @cash_flow_records = CashFlow.for_current_user.order(date: :asc) # Ensure transactions are loaded
      render :index, status: :unprocessable_entity
      return
    end

    # Process the CSV file
    result = CashFlow.import_from_csv(@csv_file, Current.user)

    if result[:success]
      flash[:notice] = 'Cash flow records are successfully created.'
    else
      flash[:alert] = result[:error] || 'CSV headers must be: date, description, amount, transaction_type.'
      @cash_flow_records = CashFlow.for_current_user.order(date: :asc) # Ensure transactions are loaded
      render :index, status: :unprocessable_entity
      return
    end

    redirect_to cash_flows_path
  end

  def index
    @cash_flow_records = CashFlow.for_current_user.order(date: :asc)
  end

  def edit
    @cash_flow_records = CashFlow.for_current_user.find(params[:id])
  end

  def update
    @cash_flow_records = CashFlow.for_current_user.find(params[:id])
    if @cash_flow_records.update(cash_flow_params)
      redirect_to cash_flows_path, notice: 'Record was successfully updated.'
    else
      @cash_flow_records = CashFlow.for_current_user.all
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @cash_flow_record = CashFlow.for_current_user.find(params[:id])
    if @cash_flow_record.destroy
      render json: {message: 'Record was successfully deleted.' }, status: :ok
    else
      render json: {message: 'Failed to delete the record'}, status: :unprocessable_entity
    end
  end

  def delete_all
    CashFlow.for_current_user.delete_all

    redirect_to cash_flows_path, notice: 'All records have been deleted.'
  end

  def set_balance
    @balance = params[:starting_balance]

    if @balance.blank? || !is_number?(@balance)
      render json: {message: 'Balance must be a valid number.'}, status: :unprocessable_entity
    else
      session[:starting_balance] = @balance
      render json: { message: 'Balance was successfully set.'}
    end
  end

  def reset_balance
    session[:starting_balance] = 0
    @balance = session[:starting_balance]
    redirect_to cash_flows_path, notice: 'Balance was successfully reset.'
  end

  def add_transaction
    @transaction = Current.user.cash_flows.new(cash_flow_params)

    if @transaction.save
      redirect_to cash_flows_path, notice: 'Record was successfully saved.'
    else
      @cash_flow_records = CashFlow.for_current_user.all
      render :index, status: :unprocessable_entity
    end
  end

  private

  def cash_flow_params
    params.require(:cash_flow).permit(:date, :description, :amount, :transaction_type)
  end

  def validate_csv(file)
    return false  unless file.respond_to?(:content_type)
      content_type = file.content_type
      content_type == "text/csv"
  end

  def headers_match?(headers)
    headers.sort == CashFlow::EXPECTED_HEADERS.sort
  end

  def is_number?(string)
    true if Float(string) rescue false
  end
end

app/helpers/cash_flows_helper.rb
module CashFlowsHelper
end

app/views/cash_flows/index.html.erb
<%# UPLOAD FILES %>
<div class="py-2">
  <%= form_with model: CashFlow.new, local: true, multipart: true, data: { turbo: false } do |form| %>
    <div class="d-flex">
      <%= form.file_field :file, class: 'form-control me-2' %>
      <%= form.submit 'upload files', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
<%# ADD TRANSACTIONS MANUALLY %>
<div data-controller="transaction-form" class="mb-3 pt-2 custom-form">
    <%= form_with model: CashFlow.new, url: add_transaction_cash_flows_path, id: "add_transaction", data:{ turbo: false, action: 'submit->transaction-form-form#submit', transaction_form_target: "transactionForm" } do |form| %>
      <div class="row">
        <div class="col-md">
          <%= form.date_field :date, class: 'form-control', placeholder: 'Date' %>
        </div>
        <div class="col-md">
          <%= form.text_field :description, class: 'form-control', placeholder: 'Description' %>
        </div>
        <div class="col-md">
          <%= form.number_field :amount, class: 'form-control', placeholder: 'Amount' %>
        </div>
        <div class="col-md">
          <%= form.select :transaction_type, [["Debit", 0], ["Credit", 1]], {}, class: 'form-select' %>
        </div>
        <div class="col-md-auto">
          <%= form.submit "add transaction", class: "btn btn-outline-secondary" %>
        </div>
      </div>
    <% end %>
</div>

<div class="d-flex justify-content-between mb-2 w-100 custom-balance">
  <%# DELETE ALL TRANSACTIONS IN ONCE %>
  <div>
    <%= button_to 'delete all transactions', { action: 'delete_all' }, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-outline-primary mb-2"%>
  </div>
  <%# ADD STARTING BALANCE %>
  <div data-controller='balance-form' class="d-flex">
    <%= form_with url: set_balance_path, id: 'balance_form', data:  { turbo: false, action: 'submit->balance-form#submit', balance_form_target: 'form'} do |form| %>
      <div class="d-flex">
        <%= form.text_field :starting_balance, class: 'form-control me-2', placeholder: '0,00' %>
        <%= form.submit 'set balance', class: "btn btn-outline-secondary me-2" %>
      </div>
    <% end %>
    <%# RESET BALANCE %>
    <div>
      <%= button_to 'reset', "reset_balance", method: :post, class: "btn btn-outline-secondary ", data: { action: 'click->balance-form#reset'} %>
    </div>
  </div>
</div>

<table class="table table-sm">
  <%# HEADERS %>
  <thead>
    <tr class="table-secondary">
      <th>Date</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Balance</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%# STARTING BALANCE ROW %>
    <tr class="border-bottom">
      <td></td>
      <td>Starting balance</td>
      <td></td>
      <td><%= number_to_currency(session[:starting_balance], unit: "R$ ", separator: ",", delimiter: ".", precision: 2) %></td>
      <td></td>
    </tr>

    <%# INITIALIZE RUNNING_BALANCE %>
    <% running_balance = session[:starting_balance].to_f %>

    <%# ADD TRANSACTIONS BY UPLOADING A CSV %>
    <% if  !@cash_flow_records.nil? && @cash_flow_records.any? %>
      <% @cash_flow_records.each do | record | %>
        <tr id="record-<%= record.id%>" class="border-bottom">
          <td>
            <%= record.date.strftime("%d/%m/%y") %>
          </td>
          <td>
            <%= record.description %>
          </td>
          <%# TRANSACTIONS TYPE EXPENSES / 0 %>
            <% if record.transaction_type == 0 %>
              <td class="border-bottom expense-color no-wrap">
                <%= number_to_currency(record.amount, unit: "R$ ", separator: ",", delimiter: ".", precision: 2) %>
              </td>
            <% else %>
            <%# TRANSACTIONS TYPE RECEIVABLES / 1 %>
              <td class="border-bottom no-wrap">
                <%= number_to_currency(record.amount, unit: "R$ ", separator: ",", delimiter: ".", precision: 2) %>
              </td>
            <% end %>
            <%# SUM OR SUBTRACTION BASED ON TRANSACTION TYPE - EXPENSE OR INCOME %>
          <% if record.transaction_type == 1 %>
            <td class="border-bottom no-wrap"><%= number_to_currency(running_balance += record.amount, unit: "R$ ", separator: ",", delimiter: ".", precision: 2) %></td>
          <% else %>
            <td class="border-bottom no-wrap"><%=number_to_currency(running_balance -= record.amount, unit: "R$ ", separator: ",", delimiter: ".", precision: 2) %></td>
          <% end %>
          <%# EDIT AND DELETE ICONS %>
          <td class="d-flex justify-content-around align-items-center border border-0" role="button" data-controller="icons">
            <i class="fa-solid fa-pencil me-1" data-action="click->icons#edit" data-record-id="<%= record.id %>"></i>
            <i class="fa-solid fa-trash-can" data-action="click->icons#delete" data-record-id="<%= record.id %>"></i>
          </td>
        </tr>
        <%# HIDDEN FORM TO USE WHEN EDITING A TRANSACTION %>
        <tr id="edit-form-<%= record.id %>" style="display: none;">
          <td colspan="5">
            <%=  form_with(model: record, id: "form-#{record.id}", local: false) do |form| %>
              <div class="form-row d-flex justify-content-around align-items-center">
                <div>
                  <%= form.date_field :date %>
                </div>
                <div>
                  <%= form.text_field :description %>
                </div>
                <div>
                  <%= form.number_field :amount %>
                </div>
                <div class="d-flex justify-content-around align-items-center me-3" data-controller="icons">
                  <div>
                    <button type="submit" class="save-edit-icon text-success" data-record-id="<%= record.id%>"><i class="fa-solid fa-circle-check"></i></button>
                  </div>
                  <div>
                    <button type="button" class="cancel-edit-icon text-danger" data-action="click->icons#cancelEdit" data-record-id="<%= record.id %>"><i class="fa-solid fa-xmark"></i></button>
                  </div>
                </div>
              </div>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <p>No data to display.</p>
    <% end %>
  </tbody>
</table>