config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'reconciliations#index'

  resources :cash_flows, only: [:create, :index, :update, :destroy] do
    collection do
      post "add_transaction"
      delete 'delete_all'
    end
  end

  post "set_balance", to: "cash_flows#set_balance"
  post "reset_balance", to: "cash_flows#reset_balance"

  resources :reconciliations, only: [:new, :create, :index] do
    collection do
      delete 'delete_all'
      get 'download_pdf'
    end
  end

end

app/views/shared/_flash.html.erb
<div id="flash-messages" class="flash-container">
  <% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger mt-4" role="alert">
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-white fixed-top custom-shadow">
  <div class="container-fluid">
    <%= link_to reconciliations_path do %>
      <%= image_tag "logo.png", alt: "flow logo", width: "60px", class: "nav-brand" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse  justify-content-between" id="navbarNav">
      <div class="d-flex align-items-center ms-2">
        <% if user_signed_in? %>
          <ul class="navbar-nav nav-underline">
            <li class="nav-item">
              <a class="nav-link <%= "active" if current_page?(reconciliations_path) %>" aria-current="page" href="/reconciliations">Reconciliation</a>
            </li>
            <li class="nav-item">
              <a class="nav-link <%= "active" if current_page?(cash_flows_path) %>" href="/cash_flows">Cash-flow</a>
            </li>
          </ul>
        <% end %>
      </div>
        <% if user_signed_in? %>
          <div class="d-flex align-items-center ms-1">
            <%= link_to edit_user_registration_path, class: "nav-link me-2" do %>
              <span class="d-none d-md-inline"> <%= current_user.email %> </span>
            <% end  %>
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-link nav-link text-primary fw-bold", id: "custom-color", form: {class:"d-inline"} %>
          </div>
        <% end %>
    </div>
  </div>
</nav>