config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'reconciliations#index'

  resources :cash_flows, only: [:create, :index, :update, :destroy] do
    collection do
      post "add_transaction"
      delete 'delete_all'
    end
  end

  post "set_balance", to: "cash_flows#set_balance"
  post "reset_balance", to: "cash_flows#reset_balance"

  resources :reconciliations, only: [:new, :create, :index] do
    collection do
      delete 'delete_all'
      get 'download_pdf'
    end
  end

end

app/controllers/reconciliations_controller.rb
require 'csv'
class ReconciliationsController < ApplicationController
  def new
    @file1 = FinanceRecord.new
    @file2 = FinanceRecord2.new

    respond_to do |format|
      format.html { head :no_content}
      format.json { render json: {file1: @file1, file2: @file2} }
    end
  end

  def index
    @csv_data1 = FinanceRecord.for_current_user.all
    @csv_data2 = FinanceRecord2.for_current_user.all

    if @csv_data1.present? && @csv_data2.present?
      match(@csv_data1, @csv_data2)
    end

  end

  def create
    @file1 = params[:file1]
    @file2 = params[:file2]

    service_validator = ReconciliationCsvFileValidator.new(@file1, @file2)
    result_csv_validator = service_validator.validate

    unless result_csv_validator[:success]
      flash.now[:alert] = result_csv_validator[:error]
      render :index, status: :unprocessable_entity
      return
    end
    service_data_saver = ReconciliationDataSaver.new(@file1, @file2, FinanceRecord, FinanceRecord2)
    result_data_saver = service_data_saver.call

    if result_data_saver[:success]
      redirect_to reconciliations_path, notice: "Reconciliation completed successfully."
    else
      flash.now[:alert] = result_data_saver[:error]
      render :index, status: :unprocessable_entity
    end
  end

  def delete_all
    FinanceRecord.for_current_user.delete_all
    FinanceRecord2.for_current_user.delete_all

    redirect_to root_path, notice: "All records have been deleted."
  end

  def download_pdf
    # Initialize the variables needed for the view
    @csv_data1 = FinanceRecord.for_current_user.all
    @csv_data2 = FinanceRecord2.for_current_user.all

    # Render your HTML template
    html = render_to_string(template: 'reconciliations/pdf', layout: 'pdf')
    pdf = Grover.new(html).to_pdf

    send_data pdf,
              filename: "reconciliation.pdf",
              type: "application/pdf",
              disposition: "attachment" # "inline" to display in the browser, "attachment" to force download
  end

  private

  def match(csv_data1, csv_data2)

    csv_data1.each do |record1|
      match = csv_data2.find do |record2|
        record1[:date] == record2[:date] &&
        record1[:amount] == record2[:amount] && !record2[:reconciled]
      end
      if match
        match[:reconciled] = true
        match.save
      end
    end

    csv_data2.each do |record2|
      match = csv_data1.find do |record1|
          record2[:date] == record1[:date] &&
          record2[:amount] == record1[:amount] &&
          !record1[:reconciled]
      end
      if match
        match[:reconciled] = true
        match.save
      end
    end
  end
end

app/views/reconciliations/_tables.html.erb
<div class="row justify-content-start">
      <div class="col">
        <table class="table table-light table-sm" data-controller="highlight-rows">
          <thead class="table-secondary">
            <th>Date</th>
            <th>Description</th>
            <th>Amount</th>
          </thead>
          <tbody>
            <% @csv_data1.each do |record| %>
              <% next if record.date.blank? && record.description.blank? && record.amount.blank?%>
              <tr data-action="click->highlight-rows#changeColor">
                <td class = "<%= record.reconciled ? 'match' : 'different'   %>">
                  <div class="row-height">
                    <%= record.date.strftime('%d/%m/%y') %>
                  </div>
                </td>
                <td class = "<%= record.reconciled ? 'match' : 'different'   %>">
                  <div class="row-height">
                    <%= record.description %>
                  </div>
                </td>
                <td class = "<%= record.reconciled ? 'match' : 'different'   %>">
                  <div class="row-height amount-column">
                    <%= number_to_currency(record.amount, unit: "R$ ", separator: ",", delimiter:".", precision: 2) %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col">
        <table class="table table-light table-sm" data-controller="highlight-rows">
          <thead class="table-secondary">
            <th>Date</th>
            <th>Description</th>
            <th>Amount</th>
          </thead>
          <tbody>
            <% @csv_data2.each do |record| %>
              <% next if record.date.blank? && record.description.blank? && record.amount.blank?%>
              <tr data-action="click->highlight-rows#changeColor">
                <td class = "<%= record.reconciled ? 'match' : 'different' %>">
                  <div class="row-height">
                    <%= record.date.strftime('%d/%m/%y') %>
                  </div>
                </td>
                <td class = "<%= record.reconciled ? 'match' : 'different' %>">
                  <div class="row-height">
                    <%= record.description %>
                  </div>
                </td>
                <td class = "<%= record.reconciled ? 'match' : 'different' %>">
                  <div class="row-height amount-column">
                    <%= number_to_currency(record.amount, unit: "R$ ", separator: ",", delimiter:".", precision: 2) %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

app/views/reconciliations/index.html.erb
<div class="my-3">
  <%= form_with url: reconciliations_path, local: true, multipart: true do |form| %>
    <div class="form-group d-flex">
      <%= form.file_field :file1, class: 'form-control me-2' %>
      <%= form.file_field :file2, class: 'form-control me-2' %>
      <%= form.submit 'Upload Files', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
<% if @csv_data1.present? && @csv_data2.present? %>
  <div>
    <div class="d-flex justify-content-between mb-2">
      <%= button_to 'Delete All Records', { action: 'delete_all' }, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-secondary mb-2"%>
      <%= link_to 'Download PDF', download_pdf_reconciliations_path, class: 'btn btn-outline-primary mb-2', target: '_blank' %>
    </div>
    <%= render partial: 'tables', locals: { csv_data1: @csv_data1, csv_data2: @csv_data2 } %>
  </div>
<% else %>
  <p>No data to display.</p>
<% end %>

app/views/reconciliations/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reconciliation PDF</title>
    <meta charset="UTF-8">
    <%= stylesheet_link_tag 'application', media: 'all' %> <!-- CSS -->
  </head>
  <body>
    <% if @csv_data1.present? && @csv_data2.present? %>
      <%= render partial: 'tables', locals: { csv_data1: @csv_data1, csv_data2: @csv_data2 } %>
    <% else %>
      <p>No data available to display.</p>
    <% end %>
  </body>
</html>

app/views/reconciliations/show.html.erb
<% if @csv_data1.any? && @csv_data2.any? %>
  <div class="container mt-4">
    <%= button_to 'Delete All Records', { action: 'delete_all' }, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning"%>
    <div class="row justify-content-start">
      <div class="col">
        <h3 class="title">Records CSV 1</h3>
        <table class="table table-secondary table-sm table-striped" data-controller="highlight-rows">
          <tr>
            <th>Date</th>
            <th>Description</th>
            <th>Amount</th>
          </tr>
          <tbody>
            <% @csv_data1.each do |record| %>
              <% next if record.date.blank? && record.description.blank? && record.amount.blank?%>
              <tr data-action="click->highlight-rows#changeColor">
                <td class = "<%= record.reconciled ? 'match' : 'different'   %>">
                  <div class="row-height">
                    <%= record.date %>
                  </div>
                </td>
                <td class = "<%= record.reconciled ? 'match' : 'different'   %>">
                  <div class="row-height">
                    <%= record.description %>
                  </div>
                </td>
                <td class = "<%= record.reconciled ? 'match' : 'different'   %>">
                  <div class="row-height">
                    <%= record.amount %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col">
        <h3 class="title">Records CSV 2</h3>
        <table class="table table-secondary table-sm table-striped" data-controller="highlight-rows">
          <tr>
            <th>Date</th>
            <th>Description</th>
            <th>Amount</th>
          </tr>
          <% @csv_data2.each do |record| %>
            <% next if record.date.blank? && record.description.blank? && record.amount.blank?%>
            <tr data-action="click->highlight-rows#changeColor">
              <td class = "<%= record.reconciled ? 'match' : 'different' %>">
                <div class="row-height">
                  <%= record.date %>
                </div>
              </td>
              <td class = "<%= record.reconciled ? 'match' : 'different' %>">
                <div class="row-height">
                  <%= record.description %>
                </div>
              </td>
              <td class = "<%= record.reconciled ? 'match' : 'different' %>">
                <div class="row-height">
                  <%= record.amount %>
                </div>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
<% else %>
  <p>No data to display.</p>
<% end %>